#!/usr/bin/perl
#
# Copyright (c) 2018 sasairc
# Released under the MIT license.
# see https://github.com/sasairc/lsoac/blob/master/LICENSE
#

use strict;
use warnings;
use utf8;
use Encode;
use JSON;
use YAML::Tiny;
use LWP::UserAgent;
use Net::Twitter::Lite::WithAPIv1_1;

my $config = (YAML::Tiny->read('./config.yml'))->[0];

sub do_tweet
{
    my $sender;

    $sender = Net::Twitter::Lite::WithAPIv1_1->new (
        consumer_key        => $config->{'TWITTER_CONSUMER_KEY'},
        consumer_secret     => $config->{'TWITTER_CONSUMER_SECRET'},
        access_token        => $config->{'TWITTER_ACCESS_TOKEN'},
        access_token_secret => $config->{'TWITTER_ACCESS_TOKEN_SECRET'},
        ssl => 1,
    );

    return $sender->update(decode_utf8($_[0]));
}

sub main
{
    my ($day, $ua, $res, $data, @data_arr);

    $day = <>;
    $ua = LWP::UserAgent->new;
    $res = $ua->get($config->{'API_URL'}, "accept" => "application/json");
    $data = JSON->new()->utf8(0)->decode($res->content);
    @data_arr = @{$data->{posts}};
    foreach (@data_arr) {
        if ($_->{url} && $day < $_->{day}) {
            $day = $_->{day};
            do_tweet("$_->{title} by $_->{author}: $_->{url}\n");
        }
    }
    print $day;
}

main();
